version: "3.8"

services:
    goapi:
        build:
            context: ./backend/gocms/
            dockerfile: Dockerfile
            target: init
        image: api-go-cms
        container_name: gocms
        restart: always
        ports:
            - "3000:3000"
        env_file:
            - backend/gocms/.env
            - backend/gocms/.test.env
        environment:
            FROM_DOCKER: "true"
#            GO_API_PORT: ${GO_API_PORT}
#            GO_API_DB_HOST: ${GO_API_DB_HOST}
#            GO_API_DB_PORT: ${GO_API_DB_PORT}
#            GO_API_DB_USER: ${GO_API_DB_USER}
#            GO_API_DB_PASSWORD: ${GO_API_DB_PASSWORD}
#            GO_API_DB_NAME: ${GO_API_DB_NAME}
#            GO_API_PUB_KEY: ${GO_API_PUB_KEY}
#            GO_API_PRIV_KEY: ${GO_API_PRIV_KEY}
#            GO_API_TOKEN_EXPIRATION: ${GO_API_TOKEN_EXPIRATION}
        networks:
            frontend:
                aliases:
                    - golbapi
            default:
                aliases:
                    - golbapi
        depends_on:
            - db

    db:
        image: mariadb:10.5.9
        container_name: golb-db
        env_file:
            - backend/db/.mysql.env
#        environment:
#            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#            MYSQL_DATABASE: ${MYSQL_DATABASE}
#            MYSQL_USER: ${MYSQL_USER}
#            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "33306:3306"
        volumes:
            - ./backend/db/data/mysql:/var/lib/mysql
            - ./backend/db/scripts:/docker-entrypoint-initdb.d
        networks:
            default:
                aliases:
                    - golbdb

    blog-ui:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        networks:
            frontend:
                aliases:
                    - ui


networks:
    default:
        name: golb-backend
    frontend:
        name: golb-frontend
