version: "3.8"

services:
    goapi:
        build: ./backend/gocms
        image: api-go-cms
        container_name: gocms
        restart: always
        ports:
            - "3000:3000"
        environment:
            FROM_DOCKER: "true"
            GO_API_PORT: 3000
            GO_API_DB_HOST: golbdb
            GO_API_DB_PORT: 3306
            GO_API_DB_USER: golb_dev
            GO_API_DB_PASSWORD: 100PerApi
            GO_API_DB_NAME: golb
            GO_API_PUB_KEY: /etc/golb/certificates/app.rsa.pub
            GO_API_PRIV_KEY: /etc/golb/certificates/app.rsa
        networks:
            frontend:
                aliases:
                    - golbapi
            default:
                aliases:
                    - golbapi
        depends_on:
            - db

    db:
        image: mariadb:10.5.9
        container_name: golb-db
        environment:
            MYSQL_ROOT_PASSWORD: 100PerMariadb
            MYSQL_DATABASE: golb
            MYSQL_USER: golb_dev
            MYSQL_PASSWORD: 100PerApi
        ports:
            - "33306:3306"
        volumes:
            - ./backend/db/data/mysql:/var/lib/mysql
            - ./backend/db/scripts:/docker-entrypoint-initdb.d
        networks:
            default:
                aliases:
                    - golbdb

    blog-ui:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: 'production-stage'
        image: ui-vue-cms:1.0.0-production
        container_name: vuecms-ui-production
        ports:
            - "80:80"
        networks:
            frontend:
                aliases:
                    - ui
        depends_on:
            - goapi

networks:
    default:
        name: golb-backend
    frontend:
        name: golb-frontend
