version: "3.8"

services:
    goapi:
        build:
            context: ./backend/gocms/
            dockerfile: Dockerfile
            target: init
        image: api-go-cms
        container_name: gocms
        restart: always
        ports:
            - "3000:3000"
        env_file:
            - backend/gocms/.env
            - backend/gocms/.test.env
        environment:
            FROM_DOCKER: "true"
            VIRTUAL_HOST: api.golb.io
        networks:
            frontend:
                aliases:
                    - golbapi
            default:
                aliases:
                    - golbapi
        depends_on:
            - db

    db:
        image: mariadb:10.5.9
        container_name: golb-db
        env_file:
            - backend/db/.mysql.env
        ports:
            - "33306:3306"
        volumes:
            - ./backend/db/data/mysql:/var/lib/mysql
            - ./backend/db/scripts:/docker-entrypoint-initdb.d
        networks:
            default:
                aliases:
                    - golbdb

    blog-ui:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        networks:
            frontend:
                aliases:
                    - ui

    ingress:
        image: jwilder/nginx-proxy:alpine
        container_name: ingress-nginx
        ports:
        - "80:80"
        volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            frontend:
                aliases:
                    - proxy
        depends_on:
            - goapi
            - blog-ui

networks:
    default:
        name: golb-backend
    frontend:
        name: golb-frontend
