apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      role: vuecms-ui-prod
  template:
    metadata:
      labels:
        role: vuecms-ui-prod
    spec:
      imagePullSecrets:
      - name: docker-cfg
      containers:
      - name: vuecms-ui-prod
        image: registry.digitalocean.com/golb-repository/ui-vue-cms:0.0.1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: blog-ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    role: vuecms-ui-prod
